"""Hermes research gate plugin — auto-generated by maru setup."""

try:
    from maru_deep_pro_search.cli.agents.hermes_plugin import register
except Exception as exc:
    import warnings

    warnings.warn(f"maru plugin import failed: {exc}", stacklevel=2)

    def register(ctx):
        ctx.inject_message(
            "[MARU] Plugin import failed. Is maru-deep-pro-search installed?", role="system"
        )
