"""Generate CI/CD workflow templates for automated research."""

from __future__ import annotations

import argparse
from pathlib import Path

from .env_check import bold, green, yellow

_GITHUB_WORKFLOW_TEMPLATE = """name: Maru Deep Research

on:
  pull_request:
    types: [opened, synchronize]
  issues:
    types: [opened]
  workflow_dispatch:
    inputs:
      query:
        description: "Research query"
        required: true
        default: "latest security best practices"

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  research:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
          cache-dependency-path: "**/pyproject.toml"

      - name: Install maru-deep-pro-search
        run: |
          pip install maru-deep-pro-search

      - name: Run deep research
        id: research
        env:
          MARU_QUERY: ${{ github.event.inputs.query || github.event.pull_request.title || github.event.issue.title || github.event.pull_request.body || 'general research' }}
        run: |
          echo "query=$MARU_QUERY" >> "$GITHUB_OUTPUT"
          python -m maru_deep_pro_search.server research "$MARU_QUERY" --output research-report.md

      - name: Upload research report
        uses: actions/upload-artifact@v4
        with:
          name: research-report
          path: research-report.md

      - name: Post research summary to PR
        if: github.event_name == 'pull_request' && success()
        uses: actions/github-script@v7
        env:
          MARU_QUERY: ${{ steps.research.outputs.query }}
        with:
          script: |
            const fs = require('fs');
            const report = fs.readFileSync('research-report.md', 'utf8');

            // Extract Key Findings
            const findingsMatch = report.match(/### Key Findings\s*\n\n([\s\S]*?)(?=\n### Sources|\n### Suggested Follow-up)/);
            let findings = findingsMatch ? findingsMatch[1].trim() : '';
            findings = findings.split('\n').slice(0, 5).join('\n'); // max 5 bullets
            if (findings.length > 1200) findings = findings.substring(0, 1200) + '...';

            // Extract Top Sources (first 3)
            const sourcesSection = report.match(/### Sources\s*\n\n([\s\S]*?)(?=\n### Suggested Follow-up)/);
            let topSources = '';
            if (sourcesSection) {
              const entries = sourcesSection[1].match(/#{3,4}\s*\[\d+\][\s\S]*?(?=\n#{3,4}\s*\[|\n### Suggested|$)/g) || [];
              topSources = entries.slice(0, 3).map((entry, idx) => {
                const titleMatch = entry.match(/#{3,4}\s*\[\d+\]\s*(.+?)(?:\n|https?)/);
                const urlMatch = entry.match(/(https?:\/\/[^\s\n]+)/);
                const scoreMatch = entry.match(/_score:\s*([\d.]+)/);
                const title = titleMatch ? titleMatch[1].replace(/\*\*/g, '').trim() : 'Unknown';
                const url = urlMatch ? urlMatch[1] : '';
                const score = scoreMatch ? scoreMatch[1] : '';
                return `${idx + 1}. **[${title}](${url})**${score ? ` (score: ${score})` : ''}`;
              }).join('\n');
            }

            const body = `## 🔍 Maru Deep Research Auto-Report

**Query:** \`${process.env.MARU_QUERY}\`

### Key Findings
${findings || '_No findings extracted_'}

### Top Sources
${topSources || '_No sources extracted_'}

<details>
<summary>📄 View Full Report</summary>

\`\`\`markdown
${report}
\`\`\`
</details>

<sub>🤖 Auto-generated by [maru-deep-pro-search](https://github.com/claudianus/maru-deep-pro-search) · [View Run](${context.payload.repository.html_url}/actions/runs/${context.runId})</sub>`;

            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });

      - name: Post research summary to Issue
        if: github.event_name == 'issues' && success()
        uses: actions/github-script@v7
        env:
          MARU_QUERY: ${{ steps.research.outputs.query }}
        with:
          script: |
            const fs = require('fs');
            const report = fs.readFileSync('research-report.md', 'utf8');

            const findingsMatch = report.match(/### Key Findings\s*\n\n([\s\S]*?)(?=\n### Sources|\n### Suggested Follow-up)/);
            let findings = findingsMatch ? findingsMatch[1].trim() : '';
            findings = findings.split('\n').slice(0, 5).join('\n');
            if (findings.length > 1200) findings = findings.substring(0, 1200) + '...';

            const sourcesSection = report.match(/### Sources\s*\n\n([\s\S]*?)(?=\n### Suggested Follow-up)/);
            let topSources = '';
            if (sourcesSection) {
              const entries = sourcesSection[1].match(/#{3,4}\s*\[\d+\][\s\S]*?(?=\n#{3,4}\s*\[|\n### Suggested|$)/g) || [];
              topSources = entries.slice(0, 3).map((entry, idx) => {
                const titleMatch = entry.match(/#{3,4}\s*\[\d+\]\s*(.+?)(?:\n|https?)/);
                const urlMatch = entry.match(/(https?:\/\/[^\s\n]+)/);
                const scoreMatch = entry.match(/_score:\s*([\d.]+)/);
                const title = titleMatch ? titleMatch[1].replace(/\*\*/g, '').trim() : 'Unknown';
                const url = urlMatch ? urlMatch[1] : '';
                const score = scoreMatch ? scoreMatch[1] : '';
                return `${idx + 1}. **[${title}](${url})**${score ? ` (score: ${score})` : ''}`;
              }).join('\n');
            }

            const body = `## 🔍 Maru Deep Research Auto-Report

**Query:** \`${process.env.MARU_QUERY}\`

### Key Findings
${findings || '_No findings extracted_'}

### Top Sources
${topSources || '_No sources extracted_'}

<details>
<summary>📄 View Full Report</summary>

\`\`\`markdown
${report}
\`\`\`
</details>

<sub>🤖 Auto-generated by [maru-deep-pro-search](https://github.com/claudianus/maru-deep-pro-search) · [View Run](${context.payload.repository.html_url}/actions/runs/${context.runId})</sub>`;

            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });
"""


def cmd_generate_workflow(args: argparse.Namespace) -> int:
    """Generate a GitHub Actions workflow file for automated research."""
    path = Path(".github/workflows/maru-research.yml")
    if path.exists() and not args.force:
        print(yellow(f"⚠ Workflow already exists at {path}"))
        print("   Use --force to overwrite")
        return 1

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(_GITHUB_WORKFLOW_TEMPLATE, encoding="utf-8")
    print(green(f"✓ Generated workflow: {path}"))
    print(f"  {bold('Trigger:')} PR open/sync, issue open, or manual dispatch")
    print(f"  {bold('Install:')} pip install maru-deep-pro-search")
    print(f"  {bold('Features:')}")
    print(f"    • pip caching (speeds up repeated runs)")
    print(f"    • Auto-posts research summary as PR/Issue comment")
    print(f"    • Artifacts uploaded for full report download")
    print(f"    • PR body fallback when title is too short")
    return 0


def main(argv: list[str] | None = None) -> int:
    """Generate CI/CD workflow templates for automated research."""
    parser = argparse.ArgumentParser(
        prog="maru-deep-pro-search workflow",
        description="Generate CI/CD workflow templates for automated research pipelines.",
        epilog="Example: maru-deep-pro-search workflow --force",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite existing workflow file if it exists",
    )
    args = parser.parse_args(argv)
    return cmd_generate_workflow(args)
