"""Generate CI/CD workflow templates for automated research."""

from __future__ import annotations

import argparse
from pathlib import Path

from .env_check import bold, green, yellow

_GITHUB_WORKFLOW_TEMPLATE = """name: Maru Deep Research

on:
  pull_request:
    types: [opened, synchronize]
  issues:
    types: [opened]
  workflow_dispatch:
    inputs:
      query:
        description: "Research query"
        required: true
        default: "latest security best practices"

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  research:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
          cache-dependency-path: "**/pyproject.toml"

      - name: Install maru-deep-pro-search
        run: |
          pip install git+https://github.com/${{ github.repository }}.git@${{ github.head_ref || github.ref_name }}

      - name: Run deep research
        id: research
        env:
          MARU_QUERY: ${{ github.event.inputs.query || github.event.pull_request.title || github.event.issue.title || 'general research' }}
        run: |
          echo "query=$MARU_QUERY" >> "$GITHUB_OUTPUT"
          python -m maru_deep_pro_search.server research "$MARU_QUERY" --output research-report.md

      - name: Upload research report
        uses: actions/upload-artifact@v4
        with:
          name: research-report
          path: research-report.md

      - name: Post research summary to PR
        if: github.event_name == 'pull_request' && success()
        env:
          GH_TOKEN: ${{ github.token }}
          QUERY: ${{ steps.research.outputs.query }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO: ${{ github.repository }}
          RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        run: |
          # Build PR comment body
          {
            echo "## 🔍 Maru Deep Research Auto-Report"
            echo ""
            echo "**Query:** \`$QUERY\`"
            echo ""
            echo "### Key Findings"
            sed -n '/### Key Findings/,/### Sources/p' research-report.md | tail -n +3 | head -n 8
            echo ""
            echo "### Top Sources"
            sed -n '/### Sources/,/### Suggested Follow-up/p' research-report.md | tail -n +3 | head -n 24
            echo ""
            echo "<details>"
            echo "<summary>📄 View Full Report</summary>"
            echo ""
            echo '\`\`\`markdown'
            cat research-report.md
            echo '\`\`\`'
            echo "</details>"
            echo ""
            echo "<sub>🤖 Auto-generated by [maru-deep-pro-search](https://github.com/claudianus/maru-deep-pro-search) · [View Run]($RUN_URL)</sub>"
          } > comment.md
          gh pr comment "$PR_NUMBER" --body-file comment.md --repo "$REPO"

      - name: Post research summary to Issue
        if: github.event_name == 'issues' && success()
        env:
          GH_TOKEN: ${{ github.token }}
          QUERY: ${{ steps.research.outputs.query }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          REPO: ${{ github.repository }}
          RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        run: |
          # Build Issue comment body
          {
            echo "## 🔍 Maru Deep Research Auto-Report"
            echo ""
            echo "**Query:** \`$QUERY\`"
            echo ""
            echo "### Key Findings"
            sed -n '/### Key Findings/,/### Sources/p' research-report.md | tail -n +3 | head -n 8
            echo ""
            echo "### Top Sources"
            sed -n '/### Sources/,/### Suggested Follow-up/p' research-report.md | tail -n +3 | head -n 24
            echo ""
            echo "<details>"
            echo "<summary>📄 View Full Report</summary>"
            echo ""
            echo '\`\`\`markdown'
            cat research-report.md
            echo '\`\`\`'
            echo "</details>"
            echo ""
            echo "<sub>🤖 Auto-generated by [maru-deep-pro-search](https://github.com/claudianus/maru-deep-pro-search) · [View Run]($RUN_URL)</sub>"
          } > comment.md
          gh issue comment "$ISSUE_NUMBER" --body-file comment.md --repo "$REPO"
"""


def cmd_generate_workflow(args: argparse.Namespace) -> int:
    """Generate a GitHub Actions workflow file for automated research."""
    path = Path(".github/workflows/maru-research.yml")
    if path.exists() and not args.force:
        print(yellow(f"⚠ Workflow already exists at {path}"))
        print("   Use --force to overwrite")
        return 1

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(_GITHUB_WORKFLOW_TEMPLATE, encoding="utf-8")
    print(green(f"✓ Generated workflow: {path}"))
    print(f"  {bold('Trigger:')} PR open/sync, issue open, or manual dispatch")
    print(f"  {bold('Install:')} pip install maru-deep-pro-search")
    print(f"  {bold('Features:')}")
    print(f"    • pip caching (speeds up repeated runs)")
    print(f"    • Auto-posts research summary as PR/Issue comment")
    print(f"    • Artifacts uploaded for full report download")
    return 0


def main(argv: list[str] | None = None) -> int:
    """Generate CI/CD workflow templates for automated research."""
    parser = argparse.ArgumentParser(
        prog="maru-deep-pro-search workflow",
        description="Generate CI/CD workflow templates for automated research pipelines.",
        epilog="Example: maru-deep-pro-search workflow --force",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite existing workflow file if it exists",
    )
    args = parser.parse_args(argv)
    return cmd_generate_workflow(args)
